function [  xTPprop,xTPpropH,xTPpropW,...
            xTPprop2,xTPpropH2,xTPpropW2] = ...
                computeMetrics(...
                    labelsLocal, ...
                    labelsLocalH, ...
                    labelsLocalW, ...
                    constraints_array_H, constraints_array_W, ...
                    subtemp, subtempH, ...
                    nsubtemp, nsubtempH)

    %% Metrics Roof 
    sub_y_roof = labelsLocal;
    xTPprop2 = [ ...
       sum((subtemp==1) .* (sub_y_roof==1|sub_y_roof==4))./sum(subtemp==1) ; ...
       sum((subtemp==2) .* (sub_y_roof==1))./sum(subtemp==2) ; ...
       sum((subtemp==3) .* (sub_y_roof==1|sub_y_roof==2))./sum(subtemp==3) ; ...
       sum((subtemp==4) .* (sub_y_roof==1|sub_y_roof==2))./sum(subtemp==4) ; ...
       sum((subtemp==5) .* (sub_y_roof==1|sub_y_roof==2))./sum(subtemp==5) ; ...
       sum((subtemp==6) .* (sub_y_roof==1|sub_y_roof==3))./sum(subtemp==6) ; ...
       sum((subtemp==7) .* (sub_y_roof==1))./sum(subtemp==7) ...
       ].*sum(nsubtemp)./(nsubtemp.*sum(nsubtemp~=0));
    xTPprop2(isnan(xTPprop2)) = 0;
    sum_weights = sum(nsubtemp)./(nsubtemp.*sum(nsubtemp~=0));
    sum_weights(isinf(sum_weights)) = 0;
    xTPprop2 = sum(xTPprop2)./sum(sum_weights);
    xTPprop = (1./size(sub_y_roof,1)) .* sum(...
                                       (subtemp==1) .* (sub_y_roof==1|sub_y_roof==4) + ...
                                       (subtemp==2) .* (sub_y_roof==1) + ...
                                       (subtemp==3) .* (sub_y_roof==1|sub_y_roof==2) + ...
                                       (subtemp==4) .* (sub_y_roof==1|sub_y_roof==2) + ...
                                       (subtemp==5) .* (sub_y_roof==1|sub_y_roof==2) + ...
                                       (subtemp==6) .* (sub_y_roof==1|sub_y_roof==3) + ...
                                       (subtemp==7) .* (sub_y_roof==1) ...
                                       );

    %% Metrics Height
    true_centroidH_index = find(constraints_array_H(:,3)>0);
    sub_y_height = true_centroidH_index(labelsLocalH); %range is 1 to 6, cat
    xTPpropH2 = [ ...
       sum( (subtempH==1) .* (sub_y_height==1|sub_y_height==2) )./sum(subtempH==1) ; ...
       sum( (subtempH==2) .* (sub_y_height==2|sub_y_height==3|sub_y_height==4) )./sum(subtempH==2) ; ...
       sum( (subtempH==3) .* (sub_y_height==3|sub_y_height==4|sub_y_height==5) )./sum(subtempH==3) ; ...
       sum( (subtempH==4) .* (sub_y_height==4|sub_y_height==5) )./sum(subtempH==4) ; ...
       sum( (subtempH==5) .* (sub_y_height==5|sub_y_height==6) )./sum(subtempH==5) ; ...
       sum( (subtempH==6) .* (sub_y_height==6) )./sum(subtempH==6) ...
       ].*sum(nsubtempH)./(nsubtempH.*sum(nsubtempH~=0));
    sum_weightsH = sum(nsubtempH)./(nsubtempH.*sum(nsubtempH~=0));
    sum_weightsH(isinf(sum_weightsH)) = 0;
    xTPpropH2(isnan(xTPpropH2)) = 0;
    xTPpropH2 = sum(xTPpropH2)./sum(sum_weightsH);
    xTPpropH = (1./size(sub_y_height,1)) .* sum(...
                                       (subtempH==1) .* (sub_y_height==1|sub_y_height==2) + ...
                                       (subtempH==2) .* (sub_y_height==2|sub_y_height==3|sub_y_height==4) + ...
                                       (subtempH==3) .* (sub_y_height==3|sub_y_height==4|sub_y_height==5) + ...
                                       (subtempH==4) .* (sub_y_height==4|sub_y_height==5) + ...
                                       (subtempH==5) .* (sub_y_height==5|sub_y_height==6) + ...
                                       (subtempH==6) .* (sub_y_height==6) ...
                                       );

    %% Metrics Wall
    true_centroidW_index = find(constraints_array_W(:,3)>0);
    sub_y_wall = true_centroidW_index(labelsLocalW); 
    xTPpropW2 = [ ...
       sum( (subtemp==1) .* (sub_y_wall==1|sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==5|sub_y_wall==6|sub_y_wall==7|sub_y_wall==8) )./sum(subtemp==1) ; ...
       sum( (subtemp==2) .* (sub_y_wall==1|sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) )./sum(subtemp==2) ; ...
       sum( (subtemp==3) .* (sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==6|sub_y_wall==8) )./sum(subtemp==3) ; ...
       sum( (subtemp==4) .* (sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) )./sum(subtemp==4) ; ...
       sum( (subtemp==5) .* (sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) )./sum(subtemp==5) ; ...
       sum( (subtemp==6) .* (sub_y_wall==4) )./sum(subtemp==6) ; ...
       sum( (subtemp==7) .* (sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) )./sum(subtemp==7) ...
       ].*sum(nsubtemp)./(nsubtemp.*sum(nsubtemp~=0));
    xTPpropW2(isnan(xTPpropW2)) = 0;
    xTPpropW2 = sum(xTPpropW2)./sum(sum_weights);
    xTPpropW = (1./size(sub_y_wall,1)) .* sum(...
                                       (subtemp==1) .* (sub_y_wall==1|sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==5|sub_y_wall==6|sub_y_wall==7|sub_y_wall==8) + ...
                                       (subtemp==2) .* (sub_y_wall==1|sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) + ...
                                       (subtemp==3) .* (sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==6|sub_y_wall==8) + ...
                                       (subtemp==4) .* (sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) + ...
                                       (subtemp==5) .* (sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) + ...
                                       (subtemp==6) .* (sub_y_wall==4) + ...
                                       (subtemp==7) .* (sub_y_wall==2|sub_y_wall==3|sub_y_wall==4|sub_y_wall==6) ...
                                       );


end

