function [  sub_label_roofwall, ...
            sub_label_height, ...
            indtemp, ...
            subtemp, subtempH, ...
            unique_subtemp,unique_subtempH, ...
            nsubtemp, nsubtempH] = ...
            preprocessLabels(btype_label, ...
                             label_height, ...
                             ind)

    sub_label_roofwall  = sparse(double(btype_label(ind)));
    sub_label_height = sparse(double(label_height(ind)));
    sub_label_height_cat = ...
       ((sub_label_height>0)&(sub_label_height<6))              .* 1 + ...
       ((sub_label_height>=6)&(sub_label_height<9))             .* 2 + ...
       ((sub_label_height>=9)&(sub_label_height<12))            .* 3 + ...
       ((sub_label_height>=12)&(sub_label_height<21))           .* 4 + ... 
       ((sub_label_height>=21)&(sub_label_height<24))           .* 5 + ...  
       ((sub_label_height>=24))                                 .* 6;       
    indtemp = find(sub_label_roofwall>0 & sub_label_roofwall<=7 & sub_label_height>0);
    subtemp = full(sub_label_roofwall(indtemp));
    subtempH = full(sub_label_height_cat(indtemp));
    unique_subtemp = unique(subtemp);
    unique_subtempH = unique(subtempH);
    nsubtemp = histcounts(subtemp,1:8)';
    nsubtempH = histcounts(subtempH,1:7)';

end

