clear, clc, close
cd '/Users/joshuadimasaka/Desktop/PhD/GitHub/rwa'

data = readtable("census2022.csv", 'VariableNamingRule', 'preserve');
nDwellings_rur = data.nDwellings_rur;
nDwellings_urb = data.nDwellings_urb;

T = readtable("macro_taxonomy_table.csv");
height_table = readtable("height_table.csv");
dwelling_table = readtable("dwelling_table.csv");

T.id = string(T.settlement) + ...
    " - " + T.category + ...
    " - " + T.macro_taxonomy;
T.height_class = repelem("TBD",size(T.id,1))';
T.height_classprob = zeros(size(T.id,1),1);
T.dwelling_class = repelem("TBD",size(T.id,1))';
T.dwelling_classprob = zeros(size(T.id,1),1);
T.ndwelling_per_bldg = zeros(size(T.id,1),1);
T_id = unique(T.id);
T_new = T;

for i = 1:numel(T_id)

    addtl_row = sum(height_table.macro_taxonomy == ...
        string(T.macro_taxonomy(i))) - 1;
    if addtl_row ~= 0
        for j = 1:addtl_row
            T_new = [T_new; T(i,:)];
        end
    end
    T_new.height_class(T_new.id == T.id(i)) = ...
        height_table.height_class(height_table.macro_taxonomy == string(T.macro_taxonomy(i)));
    T_new.height_classprob(T_new.id == T.id(i)) = ...
        height_table.height_proportion(height_table.macro_taxonomy == string(T.macro_taxonomy(i)));
    
end

T_new.id2 = (1:size(T_new,1))';
T_new_new = T_new;
for k = 1:size(T_new,1)

    addtl_row = sum(dwelling_table.height_class == ...
            T_new.height_class(k)) - 1;
    if addtl_row ~= 0
        for j = 1:addtl_row
            T_new_new = [T_new_new; T_new(k,:)];
        end
    end

    T_new_new.dwelling_class(T_new_new.id2 == T_new.id2(k)) = ...
        dwelling_table.classification(dwelling_table.height_class == string(T_new.height_class(k)));
    T_new_new.dwelling_classprob(T_new_new.id2 == T_new.id2(k)) = ...
        dwelling_table.classification_proportion(dwelling_table.height_class == string(T_new.height_class(k)));
    T_new_new.ndwelling_per_bldg(T_new_new.id2 == T_new.id2(k)) = ...
        dwelling_table.dwellings_per_building(dwelling_table.height_class == string(T_new.height_class(k)));

end


n_urban = sum(T_new_new.settlement=="Urban");
n_rural = sum(T_new_new.settlement=="Rural");
Q = table;

for s = 1:size(data,1)

    % multiplier for material
    temp = table2array(data(s,14:27));
    temp(isnan(temp))=0;
    temp = temp./(sum(temp,2)./100)./100;
    for g = 1:size(T_new_new,1) 
        idx = find(data.Properties.VariableNames==string(T_new_new.category(g)))-14+1;
        T_new_new(g,"WallMaterialProp") = table(temp(1,idx));
    end

    % urban
    if s == 1

        Q.Province = repelem(data.Province(s),n_urban)';
        Q.Distict = repelem(data.District(s),n_urban)';
        Q.Sector = repelem(data.Sector(s),n_urban)';
        Q.Settlement = repelem("Urban",n_urban)';

        Q.MacroTaxonomy = T_new_new.macro_taxonomy(T_new_new.settlement=="Urban");
        Q.MacroTaxonomyProp = T_new_new.macro_proportion(T_new_new.settlement=="Urban");

        Q.Material = T_new_new.category(T_new_new.settlement=="Urban");
        Q.MaterialProp = T_new_new.WallMaterialProp(T_new_new.settlement=="Urban");

        Q.HeightClass = T_new_new.height_class(T_new_new.settlement=="Urban");
        Q.HeightClassProp = T_new_new.height_classprob(T_new_new.settlement=="Urban");

        Q.TaxonomyID = T_new_new.macro_taxonomy(T_new_new.settlement=="Urban") + "+" + ...
               T_new_new.height_class(T_new_new.settlement=="Urban") + "/RES";

        Q.DwellingClass = T_new_new.dwelling_class(T_new_new.settlement=="Urban");
        Q.DwellingClassProp = T_new_new.dwelling_classprob(T_new_new.settlement=="Urban");
        Q.nDwellingByBldg = T_new_new.ndwelling_per_bldg(T_new_new.settlement=="Urban");

        Q.hhSize = repelem(data.sector_household_size(s),n_urban)';

        Q.numDwelling = data.nDwellings_urb(s) .* ...
                        T_new_new.macro_proportion(T_new_new.settlement=="Urban") .* ...
                        T_new_new.height_classprob(T_new_new.settlement=="Urban") .* ...
                        T_new_new.dwelling_classprob(T_new_new.settlement=="Urban") .* ...
                        T_new_new.WallMaterialProp(T_new_new.settlement=="Urban");

        Q.numBuilding = data.nDwellings_urb(s) .* ...
                        T_new_new.macro_proportion(T_new_new.settlement=="Urban") .* ...
                        T_new_new.height_classprob(T_new_new.settlement=="Urban") .* ...
                        T_new_new.dwelling_classprob(T_new_new.settlement=="Urban") .* ...
                        T_new_new.WallMaterialProp(T_new_new.settlement=="Urban") ./ ...
                        T_new_new.ndwelling_per_bldg(T_new_new.settlement=="Urban");

        Q.numOccupant = data.nDwellings_urb(s) .* ...
                        T_new_new.macro_proportion(T_new_new.settlement=="Urban") .* ...
                        T_new_new.height_classprob(T_new_new.settlement=="Urban") .* ...
                        T_new_new.dwelling_classprob(T_new_new.settlement=="Urban") .* ...
                        T_new_new.WallMaterialProp(T_new_new.settlement=="Urban") .* ...
                        data.sector_household_size(s);
    else
        Q = [Q; ...
        table(  repelem(data.Province(s),n_urban)',...
                repelem(data.District(s),n_urban)',...
                repelem(data.Sector(s),n_urban)',...
                repelem("Urban",n_urban)',...
                T_new_new.macro_taxonomy(T_new_new.settlement=="Urban"),...
                T_new_new.macro_proportion(T_new_new.settlement=="Urban"),...
                T_new_new.category(T_new_new.settlement=="Urban"),...
                T_new_new.WallMaterialProp(T_new_new.settlement=="Urban"),...
                T_new_new.height_class(T_new_new.settlement=="Urban"),...
                T_new_new.height_classprob(T_new_new.settlement=="Urban"),...
                T_new_new.macro_taxonomy(T_new_new.settlement=="Urban") + "+" + ...
                T_new_new.height_class(T_new_new.settlement=="Urban") + "/RES",...
                T_new_new.dwelling_class(T_new_new.settlement=="Urban"),...
                T_new_new.dwelling_classprob(T_new_new.settlement=="Urban"),...
                T_new_new.ndwelling_per_bldg(T_new_new.settlement=="Urban"),...
                repelem(data.sector_household_size(s),n_urban)',...
                data.nDwellings_urb(s) .* ...
                    T_new_new.macro_proportion(T_new_new.settlement=="Urban") .* ...
                    T_new_new.height_classprob(T_new_new.settlement=="Urban") .* ...
                    T_new_new.dwelling_classprob(T_new_new.settlement=="Urban") .* ...
                    T_new_new.WallMaterialProp(T_new_new.settlement=="Urban"),...
                data.nDwellings_urb(s) .* ...
                    T_new_new.macro_proportion(T_new_new.settlement=="Urban") .* ...
                    T_new_new.height_classprob(T_new_new.settlement=="Urban") .* ...
                    T_new_new.dwelling_classprob(T_new_new.settlement=="Urban") .* ...
                    T_new_new.WallMaterialProp(T_new_new.settlement=="Urban") ./ ...
                    T_new_new.ndwelling_per_bldg(T_new_new.settlement=="Urban"),...
                data.nDwellings_urb(s) .* ...
                    T_new_new.macro_proportion(T_new_new.settlement=="Urban") .* ...
                    T_new_new.height_classprob(T_new_new.settlement=="Urban") .* ...
                    T_new_new.dwelling_classprob(T_new_new.settlement=="Urban") .* ...
                    T_new_new.WallMaterialProp(T_new_new.settlement=="Urban") .* ...
                    data.sector_household_size(s) , ...
                'VariableNames', Q.Properties.VariableNames ) 
                ];

   

    end

    % rural
    Q = [Q; ...
        table(  repelem(data.Province(s),n_rural)',...
                repelem(data.District(s),n_rural)',...
                repelem(data.Sector(s),n_rural)',...
                repelem("Rural",n_rural)',...
                T_new_new.macro_taxonomy(T_new_new.settlement=="Rural"),...
                T_new_new.macro_proportion(T_new_new.settlement=="Rural"),...
                T_new_new.category(T_new_new.settlement=="Rural"),...
                T_new_new.WallMaterialProp(T_new_new.settlement=="Rural"),...
                T_new_new.height_class(T_new_new.settlement=="Rural"),...
                T_new_new.height_classprob(T_new_new.settlement=="Rural"),...
                T_new_new.macro_taxonomy(T_new_new.settlement=="Rural") + "+" + ...
                T_new_new.height_class(T_new_new.settlement=="Rural") + "/RES",...
                T_new_new.dwelling_class(T_new_new.settlement=="Rural"),...
                T_new_new.dwelling_classprob(T_new_new.settlement=="Rural"),...
                T_new_new.ndwelling_per_bldg(T_new_new.settlement=="Rural"),...
                repelem(data.sector_household_size(s),n_rural)',...
                data.nDwellings_rur(s) .* ...
                    T_new_new.macro_proportion(T_new_new.settlement=="Rural") .* ...
                    T_new_new.height_classprob(T_new_new.settlement=="Rural") .* ...
                    T_new_new.dwelling_classprob(T_new_new.settlement=="Rural") .* ...
                    T_new_new.WallMaterialProp(T_new_new.settlement=="Rural"),...
                data.nDwellings_rur(s) .* ...
                    T_new_new.macro_proportion(T_new_new.settlement=="Rural") .* ...
                    T_new_new.height_classprob(T_new_new.settlement=="Rural") .* ...
                    T_new_new.dwelling_classprob(T_new_new.settlement=="Rural") .* ...
                    T_new_new.WallMaterialProp(T_new_new.settlement=="Rural") ./ ...
                    T_new_new.ndwelling_per_bldg(T_new_new.settlement=="Rural"),...
                data.nDwellings_rur(s) .* ...
                    T_new_new.macro_proportion(T_new_new.settlement=="Rural") .* ...
                    T_new_new.height_classprob(T_new_new.settlement=="Rural") .* ...
                    T_new_new.dwelling_classprob(T_new_new.settlement=="Rural") .* ...
                    T_new_new.WallMaterialProp(T_new_new.settlement=="Rural") .* ...
                    data.sector_household_size(s) , ...
                'VariableNames', Q.Properties.VariableNames ) 
                ];



end